### ISSUE TITLE
dependency on lodash in bower.json is too specific

### ISSUE THREAD

**Issue by benjaminapetersen** [hawtio/hawtio-core-navigation#12]
This may apply to other dependencies as well, but having the lodash version set so specifically to `"lodash": "~3.2.0",` is very restrictive.  Lodash is upto 3.10.1 on 3.x & is backwards compatible.  I'd like to pick up a newer version in the OpenShift web console, but this dependency set in `hawtio-core-navigation"` causes bower to fail install with `ECONFLICT Unable to find suitable version for lodash`.

**Comment by benjaminapetersen** [comment]
I'd take a stab at suggesting `"lodash": ">=3.2.0 <4.0.0",` would be reasonable, the [lodash changelog](https://github.com/lodash/lodash/wiki/Changelog) looks like pretty strict semver & this range would ease version lock.

**Comment by liggitt** [comment]
No, we need an exact version to lock the built bindata.go. We can experiment with an exact version that would fit our needs though

**Comment by gashcrumb** [comment]
I'd be happy to bump this version up for sure

**Comment by liggitt** [comment]
Nm, didn't notice which repo this was against. Sure, a version range here could make sense

**Comment by gashcrumb** [comment]
Should mention you should be able to use an override in bower to sort this out as well.  But we should bump it up anyways

**Comment by benjaminapetersen** [comment]
Using a resolutions block in OpenShift's bower does seem to work to force an override:

``` javascript
"resolutions": {
    "lodash": "3.10.0"
},
```

But I prob would still prefer more flexibility in dependency definition.

**Comment by gashcrumb** [comment]
Awesome, feel free to send along a PR and I can release a new version easily enough, thanks!

**Comment by benjaminapetersen** [comment]
ok will try to hit that today!

**Comment by abkieling** [comment]
@gashcrumb I believe this issue can be closed. The change to `"lodash": ">=3.2.0 <4.0.0"` has already been made.

**Comment by gashcrumb** [comment]
Yup, agreed!
